version: '3.8'

services:
  app:
    #image: demo-app:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_REDIS_HOST: redis # Hostname Redis service
      SPRING_REDIS_PORT: 6379 # port
    depends_on:
      - redis # Ensures Redis starts before the app
    networks:
      - app-network

  redis:
    image: redis:latest
    ports:
      - "6379:6379" # all defaults
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
